add tmate action

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -28,10 +28,10 @@ jobs:
     strategy:
       matrix:
         os:
-        - ubuntu-latest
-        - ubuntu-24.04-arm
-        - macos-latest
-        - macos-15-intel
+        #- ubuntu-latest
+        #- ubuntu-24.04-arm
+        #- macos-latest
+        #- macos-15-intel
         - windows-latest
       fail-fast: false
     runs-on: ${{matrix.os}}
@@ -42,16 +42,21 @@ jobs:
         uses: crystal-lang/install-crystal@v1
 
       # install-crystal doesn't support aarch64-linux (no official tarball)
-      - if: matrix.os == 'ubuntu-24.04-arm'
-        run: |
-          curl -fsSL https://packagecloud.io/84codes/crystal/gpgkey | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/84codes_crystal.gpg > /dev/null
-          . /etc/os-release
-          echo "deb https://packagecloud.io/84codes/crystal/$ID $VERSION_CODENAME main" | sudo tee /etc/apt/sources.list.d/84codes_crystal.list
-          sudo apt-get --quiet update
-          sudo apt-get --quiet --yes install crystal
+      #- if: matrix.os == 'ubuntu-24.04-arm'
+      #  run: |
+      #    curl -fsSL https://packagecloud.io/84codes/crystal/gpgkey | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/84codes_crystal.gpg > /dev/null
+      #    . /etc/os-release
+      #    echo "deb https://packagecloud.io/84codes/crystal/$ID $VERSION_CODENAME main" | sudo tee /etc/apt/sources.list.d/84codes_crystal.list
+      #    sudo apt-get --quiet update
+      #    sudo apt-get --quiet --yes install crystal
 
-      - run: make test
-      - if: success() || failure()
-        run: make test CRFLAGS=-Dpreview_mt
-      - if: success() || failure()
-        run: make test CRFLAGS="-Dpreview_mt -Dexecution_context"
+      - name: Setup tmate session
+        uses: mxschmitt/action-tmate@v3
+        with:
+          limit-access-to-actor: true
+
+      #- run: make test
+      #- if: success() || failure()
+      #  run: make test CRFLAGS=-Dpreview_mt
+      #- if: success() || failure()
+      #  run: make test CRFLAGS="-Dpreview_mt -Dexecution_context"
